version: 2.1
jobs:
  
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
            docker build -t naesheim/whereshans_web:$CIRCLE_SHA1 .
            docker push naesheim/whereshans_web:$CIRCLE_SHA1
  
  deployApp:
    docker:
    - image: praqma/helmsman:v1.12.0-helm-v2.14.3
    steps:
      - checkout
      - run:
          command: |
            helm init --client-only
            helm package deploy/whereshans-web
            helmsman --apply -f deploy/web.toml

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build
      - deployApp:
          requires:
            - build
